name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format, Init, Plan, and Apply

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "0981736d-94a4-4f8c-84f9-ee945dfedfd2"
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: "4d17479a-8a08-4d90-a0e8-f118f777e7df"
      ARM_TENANT_ID: "e6c24c86-e9fe-4ac1-b42a-c38bf8d07958"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - name: Setup Kubernetes CLI
        uses: azure/setup-kubectl@v1
        id: install
      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=terraform plan
      - name: Terraform Apply
        id: apply
        run: terraform -chdir=terraform apply -auto-approve
